### ISSUE TITLE
How to connect and run the package ?

### ISSUE THREAD

**Issue by shameelabdullanp** [gilcu3/govee-btled-H613B#1]
Looking to contribute to this project, is there any way to connect to the bt device via commend line ?

**Comment by gilcu3** [comment]
You can run the file in the tests folder, after adding the mac of your device

**Comment by shameelabdullanp** [comment]
Added mac address and looks like no working on my machine , can you push the code without pip package

**Comment by gilcu3** [comment]
> Added mac address and looks like no working on my machine , can you push the code without pip package

If you installed the package from pypi first, the code test.py should work. Which error do you receive?

**Comment by shameelabdullanp** [comment]
```
  File "/test.py", line 5, in <module>
    from govee_btled_H613B import GoveeInstance
  File "/venv/lib/python3.9/site-packages/govee_btled_H613B/__init__.py", line 9, in <module>
    from .govee_btled_H613B import BLEAK_EXCEPTIONS, GoveeInstance
  File "/venv/lib/python3.9/site-packages/govee_btled_H613B/govee_btled_H613B.py", line 43, in <module>
    class GoveeInstance:
  File "/venv/lib/python3.9/site-packages/govee_btled_H613B/govee_btled_H613B.py", line 72, in GoveeInstance
    def rssi(self) -> int | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```
this is the error

**Comment by gilcu3** [comment]
I think that error means you should use `python3.10`
